"""empty message

Revision ID: 951a73a3f3a2
Revises: 
Create Date: 2019-02-25 17:04:26.058327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951a73a3f3a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('registered_student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.Integer(), nullable=False),
    sa.Column('student_grade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registered_student')
    op.drop_table('course')
    # ### end Alembic commands ###
